#!/usr/bin/env python3
"""Build or refresh an Obsidian vault for the job search.

Reads the workspace state - job_scraper/seen_jobs.json (every job /scrape has
seen, with /rank scores when ranked) and job_search_tracker.csv (applications) -
and writes an Obsidian vault:

  00 - MOC/Job Search - MOC.md   dashboard: counts, links, how the vault works
  06 - Job Search/Job List.md    ranked shortlist, new postings, low-fit archive
  06 - Job Search/Job Tracker.md application pipeline built from the tracker CSV
  06 - Job Search/Jobs/*.md      one note per job worth tracking (high/medium
                                 fit, ranked, or already in the tracker)

Dashboard files are regenerated on every run, but only when the existing file
carries the `generated: true` marker: a hand-written note at the same path is
never overwritten. Job notes are created when missing so hand-written notes
survive; pass --force to rewrite generated job notes.

Usage:
  python3 tools/obsidian_vault.py [--vault ~/Documents/jordy_vault] [--force]
"""

import argparse
import csv
import json
import re
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SEEN = ROOT / "job_scraper" / "seen_jobs.json"
TRACKER = ROOT / "job_search_tracker.csv"
DEFAULT_VAULT = Path.home() / "Documents" / "jordy_vault"
JOB_FOLDER = "06 - Job Search"
MOC_REL = Path("00 - MOC") / "Job Search - MOC.md"

FIT_ORDER = {"high": 0, "medium": 1, "low": 2}
OPEN_STATUSES = {"drafted", "applied", "interview", "interview_only", "offer"}


def norm(text):
    return re.sub(r"[^a-z0-9]", "", str(text or "").lower())


def yaml_str(value):
    return json.dumps(str(value), ensure_ascii=False)


def safe_name(text, max_len=110):
    text = re.sub(r"[\x00-\x1f]", "", str(text))
    for ch in '\\/:*?"<>|#^':
        text = text.replace(ch, "-")
    text = re.sub(r"\s+", " ", text).strip(" .-")
    return text[:max_len].rstrip(" .-") or "untitled"


def is_generated(path):
    if not path.is_file():
        return True
    head = path.read_text(encoding="utf-8", errors="replace")[:400]
    return "generated: true" in head


def write_generated(path, content):
    """Write a generated dashboard file; never clobber a hand-written note."""
    if not is_generated(path):
        print(f"skip (not generated by this tool): {path}")
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def load_seen():
    if not SEEN.is_file():
        raise SystemExit(f"{SEEN} not found - run /scrape first")
    doc = json.loads(SEEN.read_text(encoding="utf-8"))
    seen = doc.get("seen", doc) if isinstance(doc, dict) else {}
    if not isinstance(seen, dict):
        raise SystemExit(f"{SEEN}: expected an object of job entries")
    return {k: v for k, v in seen.items() if isinstance(v, dict)}


def load_tracker():
    if not TRACKER.is_file():
        return []
    with TRACKER.open(encoding="utf-8", newline="") as fh:
        rows = list(csv.DictReader(fh))
    return [r for r in rows if any(str(v or "").strip() for v in r.values())]


def entry_sort_key(entry):
    score = 0
    if entry.get("status") not in (None, "skipped", "expired"):
        score += 2
    if entry.get("rank_score") is not None:
        score += 1
    return score


def collect_jobs(seen, tracker_rows):
    tracked = {}
    for row in tracker_rows:
        tracked[(norm(row.get("company")), norm(row.get("role")))] = row

    merged = {}
    for key, entry in seen.items():
        ck = (norm(entry.get("company")), norm(entry.get("title")))
        tracked_row = tracked.get(ck)
        if not (entry.get("fit") in ("high", "medium") or entry.get("rank_score") is not None or tracked_row):
            continue
        candidate = dict(entry)
        candidate["_key"] = key
        candidate["_tracked"] = tracked_row
        cur = merged.get(ck)
        if cur is None:
            merged[ck] = candidate
            continue
        better, worse = (candidate, cur) if entry_sort_key(candidate) > entry_sort_key(cur) else (cur, candidate)
        for field in (
            "strengths", "gaps", "rank_score", "rank_verdict", "rank_date",
            "deadline", "language_note", "location_verdict", "language_gate",
        ):
            if better.get(field) in (None, [], "") and worse.get(field) not in (None, [], ""):
                better[field] = worse[field]
        if not better.get("_tracked"):
            better["_tracked"] = worse.get("_tracked")
        merged[ck] = better
    return list(merged.values())


def note_status(entry):
    tracked = entry.get("_tracked")
    if tracked and str(tracked.get("status") or "").strip():
        return str(tracked["status"]).strip()
    return str(entry.get("status") or "unknown")


def note_filename(company, role, used):
    base = safe_name(f"{company} - {role}")
    name = base
    n = 2
    while name.lower() in used:
        name = f"{base} ({n})"
        n += 1
    used.add(name.lower())
    return name


def wikilink(name, text):
    return f"[[{name}\\|{text}]]"


def build_note(entry):
    title = entry.get("title") or "Untitled role"
    company = entry.get("company") or "Unknown company"
    url = entry.get("url") or entry.get("_key") or ""
    status = note_status(entry)
    fit = entry.get("fit") or ""
    score = entry.get("rank_score")
    verdict = entry.get("rank_verdict")
    posted = entry.get("posted_date")
    deadline = entry.get("deadline")
    portal = entry.get("portal") or ""

    tags = ["job"]
    if fit:
        tags.append(f"fit/{fit}")
    if status:
        tags.append("status/" + status.replace(" ", "-"))

    fm = ["---", "type: job", "generated: true",
          f"company: {yaml_str(company)}",
          f"role: {yaml_str(title)}",
          f"fit: {yaml_str(fit)}" if fit else "fit:",
          f"score: {score}" if score is not None else "score:",
          f"verdict: {yaml_str(verdict)}" if verdict else "verdict:",
          f"status: {yaml_str(status)}",
          f"posted: {yaml_str(posted)}" if posted else "posted:",
          f"deadline: {yaml_str(deadline)}" if deadline else "deadline:",
          f"portal: {yaml_str(portal)}" if portal else "portal:",
          f"url: {yaml_str(url)}",
          "tags:"]
    fm += [f"  - {t}" for t in tags]
    fm.append("---")

    info = []
    if fit:
        info.append(f"**Fit:** {fit.capitalize()}")
    if score is not None:
        info.append(f"**Triage score:** {score} ({verdict})")
    info.append(f"**Status:** {status}")
    if posted:
        info.append(f"**Posted:** {posted}")
    info.append(f"**Deadline:** {deadline or 'not stated'}")

    body = [f"# {company} — {title}", "",
            "> [!info] " + " | ".join(info),
            ""]
    if url:
        body.append(f"**Posting:** [{portal or 'link'}]({url})")
    body += ["", "Links: [[Job Tracker]] · [[Job List]]"]

    strengths = entry.get("strengths") or []
    gaps = entry.get("gaps") or []
    if strengths:
        body += ["", "## Why it fits", ""] + [f"- {s}" for s in strengths]
    if gaps:
        body += ["", "## Gaps / watch-outs", ""] + [f"- {g}" for g in gaps]
    if entry.get("language_note"):
        body += ["", f"> [!warning] Language note: {entry['language_note']}"]
    body += ["", "## Notes", "", "- ", ""]
    return "\n".join(fm + body)


def build_moc(jobs, tracker_rows, note_count, ranked_count, active_count, generated, script_cmd):
    return "\n".join([
        "---", "type: moc", "generated: true", "tags:", "  - job-search", "---", "",
        "# Job Search - MOC", "",
        "Entry point for the job-search workflow. Working files live in `06 - Job Search`.",
        "",
        "[[Job List]] · [[Job Tracker]]", "",
        "## Snapshot", "",
        "| Metric | Value |",
        "|---|---|",
        f"| Jobs imported as notes | {note_count} |",
        f"| Ranked shortlist | {ranked_count} |",
        f"| Applications on file | {len(tracker_rows)} |",
        f"| Active applications | {active_count} |",
        f"| Last generated | {generated} |",
        "",
        "## How this works", "",
        "- [[Job List]] - every job worth tracking, sorted by triage score, plus a low-fit archive.",
        "- [[Job Tracker]] - application pipeline pulled from the workspace tracker.",
        "- Job notes live in `06 - Job Search/Jobs/` with fit, score, strengths, gaps, and a Notes section.",
        "- Generated files carry `generated: true`; a hand-written note at the same path is never overwritten.",
        "",
        "## Refresh", "",
        "Regenerate after `/scrape`, `/rank`, or `/outcome`:",
        "",
        "```bash",
        script_cmd,
        "```",
        "",
        "## Jobs (Dataview)", "",
        "Requires the Dataview plugin, which this vault already includes.",
        "",
        "```dataview",
        "TABLE status, score, deadline, company",
        'FROM "06 - Job Search/Jobs"',
        'WHERE status != "skipped"',
        "SORT score DESC",
        "```",
        "",
    ])


def build_job_list(jobs, seen, note_index, imported_keys, generated):
    lines = ["---", "type: list", "generated: true", "---", "",
             "# Job List", "",
             f"> [!info] Generated {generated} from `job_scraper/seen_jobs.json`. "
             "Scores are triage scores from `/rank`; run `/apply` for a full evaluation.", ""]

    ranked = sorted((e for e in jobs if e.get("rank_score") is not None),
                    key=lambda e: e["rank_score"], reverse=True)
    lines += ["## Ranked shortlist", ""]
    if ranked:
        lines += ["| # | Score | Verdict | Fit | Role | Company | Status | Deadline |",
                  "|---|-------|---------|-----|------|---------|--------|----------|"]
        for i, e in enumerate(ranked, 1):
            note = note_index.get((norm(e.get("company")), norm(e.get("title"))))
            role = e.get("title") or ""
            role_cell = wikilink(note, role) if note else role
            lines.append(
                f"| {i} | {e['rank_score']} | {e.get('rank_verdict') or ''} | "
                f"{(e.get('fit') or '').capitalize()} | {role_cell} | {e.get('company') or ''} | "
                f"{note_status(e)} | {e.get('deadline') or '-'} |"
            )
    else:
        lines.append("_Nothing ranked yet - run `/rank`._")
    lines.append("")

    fresh = [e for e in jobs if e.get("status") == "new" and e.get("rank_score") is None]
    fresh.sort(key=lambda e: str(e.get("posted_date") or ""), reverse=True)
    fresh.sort(key=lambda e: FIT_ORDER.get(e.get("fit") or "", 9))
    lines += ["## New postings (not ranked yet)", ""]
    if fresh:
        lines += ["| Fit | Role | Company | Posted |",
                  "|-----|------|---------|--------|"]
        for e in fresh:
            note = note_index.get((norm(e.get("company")), norm(e.get("title"))))
            role = e.get("title") or ""
            role_cell = wikilink(note, role) if note else role
            lines.append(f"| {(e.get('fit') or '').capitalize()} | {role_cell} | "
                         f"{e.get('company') or ''} | {e.get('posted_date') or '-'} |")
    else:
        lines.append("_No unranked new postings._")
    lines.append("")

    low = [e for e in seen.values()
           if (norm(e.get("company")), norm(e.get("title"))) not in imported_keys]
    low.sort(key=lambda e: str(e.get("posted_date") or ""), reverse=True)
    lines += ["## Low-fit archive", "",
              f"<details>", f"<summary>{len(low)} postings kept for reference (no notes, low relevance)</summary>", "",
              "| Role | Company | Posted | Link |",
              "|------|---------|--------|------|"]
    for e in low:
        role = (e.get("title") or "").replace("|", "\\|")
        company = (e.get("company") or "").replace("|", "\\|")
        url = e.get("url") or ""
        link = f"[posting]({url})" if url else "-"
        lines.append(f"| {role} | {company} | {e.get('posted_date') or '-'} | {link} |")
    lines += ["", "</details>", ""]
    return "\n".join(lines)


def build_tracker(tracker_rows, note_index, generated):
    lines = ["---", "type: tracker", "generated: true", "---", "",
             "# Job Tracker", "",
             f"> [!info] Generated {generated} from `job_search_tracker.csv`. "
             "Update applications with `/outcome` in the workspace, then re-run the vault script.", ""]

    lines += ["## Applications", ""]
    if tracker_rows:
        lines += ["| Company | Role | Status | Fit | Date | Deadline |",
                  "|---------|------|--------|-----|------|----------|"]
        for row in tracker_rows:
            company = str(row.get("company") or "").strip()
            role = str(row.get("role") or "").strip()
            note = note_index.get((norm(company), norm(role)))
            company_cell = wikilink(note, company) if note else company
            lines.append(
                f"| {company_cell} | {role} | {str(row.get('status') or '').strip()} | "
                f"{str(row.get('fit_rating') or '').strip()} | {str(row.get('date') or '').strip()} | "
                f"{str(row.get('deadline') or '').strip() or '-'} |"
            )
    else:
        lines.append("_No applications yet._")
    lines.append("")

    if tracker_rows:
        lines += ["## Submission details", ""]
        for row in tracker_rows:
            company = str(row.get("company") or "").strip()
            role = str(row.get("role") or "").strip()
            note = note_index.get((norm(company), norm(role)))
            lines += [f"### {company} — {role}", ""]
            if note:
                lines.append(f"- Job note: [[{note}]]")
            else:
                lines.append("- Job note: not in the vault (create/import first)")
            source = str(row.get("source") or "").strip()
            if source:
                lines.append(f"- Posting: {source}")
            cv_file = str(row.get("cv_file") or "").strip()
            cover_file = str(row.get("cover_letter_file") or "").strip()
            if cv_file:
                lines.append(f"- CV: `{cv_file}`")
            if cover_file:
                lines.append(f"- Cover letter: `{cover_file}`")
            notes = str(row.get("notes") or "").strip()
            if notes:
                lines.append(f"- Notes: {notes}")
            lines.append("")

    lines += ["## Follow-ups", ""]
    open_rows = [r for r in tracker_rows if str(r.get("status") or "").strip().lower() in OPEN_STATUSES]
    if open_rows:
        for row in open_rows:
            lines.append(f"- [ ] {str(row.get('company') or '').strip()} — "
                         f"{str(row.get('role') or '').strip()} "
                         f"({str(row.get('status') or '').strip()})")
    else:
        lines.append("_No open applications._")
    lines += ["", "## Status legend", "",
              "- `drafted` - CV and cover letter prepared, not sent yet",
              "- `applied` - application sent",
              "- `interview` - interview stage",
              "- `offer` - offer received",
              "- `hired` / `rejected` / `no response` / `offer declined` - closed", ""]
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser(description="Build/refresh the job-search Obsidian vault")
    ap.add_argument("--vault", type=Path, default=DEFAULT_VAULT,
                    help=f"vault directory (default: {DEFAULT_VAULT})")
    ap.add_argument("--force", action="store_true", help="rewrite existing job notes")
    args = ap.parse_args()

    seen = load_seen()
    tracker_rows = load_tracker()
    jobs = collect_jobs(seen, tracker_rows)
    generated = date.today().isoformat()

    vault = args.vault.expanduser().resolve()
    job_dir = vault / JOB_FOLDER
    jobs_dir = job_dir / "Jobs"
    jobs_dir.mkdir(parents=True, exist_ok=True)

    used = set()
    note_index = {}
    created = kept = 0
    for entry in sorted(jobs, key=lambda e: (str(e.get("company") or "").lower(),
                                             str(e.get("title") or "").lower())):
        company = entry.get("company") or "Unknown company"
        title = entry.get("title") or "Untitled role"
        name = note_filename(company, title, used)
        note_index[(norm(company), norm(title))] = name
        path = jobs_dir / f"{name}.md"
        if path.exists():
            if not is_generated(path):
                print(f"skip (not generated by this tool): {path}")
                continue
            if not args.force:
                kept += 1
                continue
        path.write_text(build_note(entry), encoding="utf-8")
        created += 1

    imported_keys = {(norm(e.get("company")), norm(e.get("title"))) for e in jobs}
    ranked_count = sum(1 for e in jobs if e.get("rank_score") is not None)
    active_count = sum(1 for r in tracker_rows
                       if str(r.get("status") or "").strip().lower() in OPEN_STATUSES)
    script_cmd = f"cd {ROOT} && python3 tools/obsidian_vault.py"

    write_generated(vault / MOC_REL,
                    build_moc(jobs, tracker_rows, len(jobs), ranked_count, active_count,
                              generated, script_cmd))
    write_generated(job_dir / "Job List.md",
                    build_job_list(jobs, seen, note_index, imported_keys, generated))
    write_generated(job_dir / "Job Tracker.md",
                    build_tracker(tracker_rows, note_index, generated))

    print(f"vault: {vault}")
    print(f"dashboard: {vault / MOC_REL}")
    print(f"job folder: {job_dir}")
    print(f"job notes: {created} written, {kept} kept")
    print(f"jobs imported: {len(jobs)} ({ranked_count} ranked)")
    print(f"applications: {len(tracker_rows)} ({active_count} active)")
    low_count = sum(1 for e in seen.values()
                    if (norm(e.get("company")), norm(e.get("title"))) not in imported_keys)
    print(f"low-fit archive rows: {low_count}")


if __name__ == "__main__":
    main()
